[package]
name = "Palette-Editor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "palette_editor"
path = "src/lib.rs"

[dependencies]
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3.70", features = ["Element", "MouseEvent", "Window", "Document"] }
js-sys = "0.3.70"
